### PR TITLE
add date_or_datetime format to value

### PR DESCRIPTION
**Pull request by fdncred**
add the ability to parse iso8601 date/datetime

### CODE REVIEW

**Comment by kubouch** [comment]
Should we introduce some extra syntax to denote the date, like `d"2022-12-22"` so we can support operators without spaces?

**Comment by fdncred** [comment]
> Should we introduce some ...

I think we can but in a separate PR. I'm not sure everyone is in agreement either. If we have `d""` do we have `i""` for `int` or `xyz""` for other types? I kind of like being complete and consistent. So, I'd rather know what the full plan is than say 1 type has this sigil and no other types have it.

**Comment by sophiajt** [comment]
@fdncred we can't support `2018-10-11` style dates as they're also now valid subtraction between three numbers. Like @kubouch says, we'll need a special date syntax now.

**Comment by fdncred** [comment]
ok, i think this is ready now. You can test this in the pest editor and pasting this in and then uncommenting them one at a time to see if they parse and then deleting it and going on to the next.
```
#d"1994-11-05T08:15:30.123456789Z"
#d"1994-11-05T08:15:30.123456789+01:00"
#d"1994-11-05T08:15:30.123456789-01:00"
#d"1994-11-05T08:15:30"
#d"1994-11-05T08:15:30Z"
#d"1994-11-05T01:01:01+03:00"
#d"1994-11-05"
```

I also moved the date_or_datetime to a lesser precedence in the value definition

**Pull request merged**
